[package]
name = "ch_8_exercises"
version = "0.1.0"
authors = ["Bruno Alliguieri <bruno.dias@ceresinvestimentos.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
